Create Add file
HatimDev-HE/Hello-Microverse pull request #3
Opened 2022-05-25 16:23 UTC by HatimDev-HE

Add file

2022-05-25 17:10 UTC, vechicin requested changes
# Hi @HatimDev-HE  ✋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🚨 


 ## Highlights ⚡ 

- [x] Linters checks passing
- [x] Correct GitHub Flow
- [x] Correct `.gitignore` use

 ## Required Changes ♻️

- [ ] You need to submit the same PR for every re-review you request. This is the 3rd PR you have submitted for this project. Please stop doing so because for future projects submitting different PR will make your requests invalid and it'll prevent you from moving forward in the curriculum.
- [ ] Please change your PR title and description to something more descriptive. Here's an example:
Title: Hello Microverse
Description: In this feature I added a header with the text `Hello Microverse` and styled it with my favorite color.

- [ ] Your README file needs to follow [this template](https://github.com/microverseinc/readme-template) as part of the [project requirements](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md). Kindly fix this.

_Check the comments under the review._

## Optional suggestions 📂 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-25 17:10 UTC, vechicin commented on .github/workflows/linters.yml
> +env:
You shouldn't change any linters configurations as stated in the [linters config](https://github.com/microverseinc/linters-config/blob/master/html-css/README.md) documentation. Kindly fix this.

2022-05-25 17:10 UTC, vechicin commented on Linter1
> +N/A
Please remove this file, it doesn't serve any functionality and it makes your project look unprofessional.

2022-05-25 17:10 UTC, vechicin commented on styles.css
> +h1 { background-color: purple; }
The requirements state that it is the color of the header, not the background color that needs to change. Kindly change the `background-color` rule to `color`.

[OPTIONAL] It is considered bad practice to use color names. I suggest you change this color to its `hex` or `rgb` equivalent.

2022-05-26 06:54 UTC, HatimDev-HE commented on .github/workflows/linters.yml
> +env:
I fixed it, I had added the git on env: but revised it later on

2022-05-26 07:35 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @HatimDev-HE, This is @sja-thedude your code reviewer.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![200w](https://user-images.githubusercontent.com/70269507/159484303-3187dacc-4a82-4263-bb1a-8d72417ce1d9.gif)

 ## Highlights
✔️ Good job so far

 ## Required Changes ♻️
- [ ] As suggested by the previous reviewer kindly add PR Description as `In this feature I added a header with the text Hello Microverse and styled it with my favorite color.` You can add description by clicking [here](https://github.com/HatimDev-HE/Hello-Microverse/pull/3#issue-1248362707) and editing the description by clicking the 3 dots as shown below in the video.

https://user-images.githubusercontent.com/70269507/170440786-439d5d02-f534-430c-a5cb-06684eb08be7.mov

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 08:16 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @HatimDev-HE ,  

Your project is complete! Great job implementing the changes requested by the previous reviewer 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Validations correctly implemented
- No linter errors
- Good readme template

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 08:18 UTC, merged